### ISSUE TITLE
Add dump() support in Twig for development purposes

### ISSUE THREAD

**Issue by bratsun** [directus/webapp-example#1]
Hi,

I cannot output arrays using dump() function in twig which comes handy during development, and looks like it’s difficult to find where twig environment is defined so it could be turned on. 

Would be great to have it configurable via config file.

Thanks!

**Comment by benhaynes** [comment]
Can't you configure Twig options here? https://github.com/directus/webapp-example/blob/master/public/index.php

**Comment by bratsun** [comment]
Ok, I was missing crucial enableDebug() line, here's the whole how-to for enabling twig dump in index.php:

1. Insert code below after this line:
`$twig = $TwigView->getEnvironment();`

2. Add extension and enable it:
```
$twig->addExtension(new \Twig_Extension_Debug());
$twig->enableDebug();
```

Dump works now, thanks!

**Comment by benhaynes** [comment]
Excellent! Thanks for following up here, @bratsun. I'll close this, but it's a good reference ticket...
