### ISSUE TITLE
Unknown column 'DT.list_view' in 'field list'

### ISSUE THREAD

**Issue by league-studio** [directus/webapp-example#2]
Tried to connect the webapp-example to Directus 6.4.0 but I'm getting this error:

`Fatal error: Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'DT.list_view' in 'field list'`

Any idea? Thanks!

**Comment by WellingGuzman** [comment]
Hey @league-studio, it seems that the `directus-database` component needs to be updated to `1.x` instead of `0.x`

Can you try updating the component?

**Comment by league-studio** [comment]
How do I update it?

**Comment by WellingGuzman** [comment]
Oh sorry, run `composer update` using terminal (if that doesn't work make sure to remove the `composer.lock` first)

**Comment by league-studio** [comment]
From the Directus root?

**Comment by league-studio** [comment]
@WellingGuzman I solved the issue, something to do with mod_rewrite and page routing.

**Comment by WellingGuzman** [comment]
@league-studio this is odd, but glad you figured it out.
